### ISSUE TITLE
Collections without services cannot be updated

### ISSUE THREAD

**Issue by kabradyUPENN** [ExLibrisGroup/alma-e-collection-quick-update#10]
I'm trying to update the access type to "perpetual" and the process doesn't consistently finish. I select ecollections, specify "replace" and "perpetual" and click "update collections". I see the processing icon load halfway then occasionally I get the confirmation that the updates happened but more frequently nothing happens. Is this a known bug?

**Comment by jweisman** [comment]
Hi @kabradyUPENN - thanks for your issue. Are you OK with us checking this in your sandbox environment? If so, please provide your sandbox URL and which collections we can try with. Thanks!

**Comment by kabradyUPENN** [comment]
yes, sure, of course

https://upenn-psb.alma.exlibrisgroup.com/SAML

you can really try with any ecollections, but if it helps, I just tried updating the first 50 results from this ecollections search

Electronic Collections (1 - 50 of 102 ) where (Keywords contains keywords "archives unbound" AND Interface Name is empty)<https://upenn-psb.alma.exlibrisgroup.com/#>

with no success. I tried selecting all 50 and updating a single field (perpetual access) and multiple fields, and also just one collection.

thanks very much for your help,
Katie

________________________________

**Comment by jweisman** [comment]
Thanks for your response. It appears from an initial look that the collections which can't be updated don't have any services, while those with services do work. Can you confirm that seems to be true from your side (try updating a couple of collections with services). 

If so, we will try to adjust the app so that it will work on collections without services.

**Comment by kabradyUPENN** [comment]
That looks to be it! Confirmed, I was able to update successfully when I only selected ecollections with services. thanks for your help.
Katie

________________________________

**Comment by jweisman** [comment]
Hi @kabradyUPENN . We released a small update which hopefully fixes this issue. Let us know how it works for you. Thanks!

**Comment by kabradyUPENN** [comment]
‘fraid not, it still stalls out halfway around the loading/processing circle animation. -klb

**Comment by jweisman** [comment]
Huh- sorry about that. We tested with Collection ID 61468393730003681 and it was successful. Which record are you using which is still problematic?

**Comment by kabradyUPENN** [comment]
welp, it’s working when I test just now these three:

61453426280003681
61453424760003681
61452951250003681

the only difference with these three compared to 61468393730003681 in our local production instance is that they are local ecollections, and in our production instance we have a service attached to 61468393730003681.

I also just had to update my Chrome this morning. I wonder whether that has anything to do with it.

Anyway, thanks for your help, and I’m glad it seems to be fixed now!

Katie

**Comment by jweisman** [comment]
Glad it's working now. Thanks for your help in making the app better!
