### ISSUE TITLE
Error when attempting to update Do not show as Full Text available in CDI even if active in Alma

### ISSUE THREAD

**Issue by straill** [ExLibrisGroup/alma-e-collection-quick-update#11]
Updating the value for Do not show as full text in CDI even if active in Alma fails. Here's the error message:

ID 61786474250001701 could not be updated: Unrecognized field "is_suppressed_from_cdi" (class com.exlibris.alma.ws.jaxb.electroniccollection.ElectronicCollection), not marked as ignorable (44 known properties: "resource_metadata", "license", "alternative_title", "is_selective", "public_note", "number", "process_type", "group_setting", "interface_override", "language_override", "cdi_only_full_text_activation", "is_local", "language", "authentication_note", "id", "url_override", "public_name", "public_name_override", "portfolios", "creator", "category_override", "proxy", "description_override", "expected_activation_date", "type_override", "note", "po_line", "access_type", "activation_date", "interface", "internal_description", "library", "description", "category", "free_override", "counter_platform", "source", "do_not_show_as_full_text_available_in_cdi_even_if_active_in_alma", "free", "url", "proxy_enabled", "type", "cdi_search_activation_status", "link"]) at [Source: java.io.ByteArrayInputStream@657e01a; line: 1, column: 1122] (through reference chain: com.exlibris.alma.ws.jaxb.electroniccollection.Electronic

Stacie Traill (University of Minnesota)

**Comment by jweisman** [comment]
Hi- thanks for you question. It looks like support for this field is brand new from the February 2021 release! So you can try it out now in your sandbox or in your production instance from February 8.

Let us know how it works for you.

**Comment by jweisman** [comment]
Closing- please reopen if there's still an issue.
