### ISSUE TITLE
Various seemingly unrelated errors when trying to update internal description field

### ISSUE THREAD

**Issue by martinpatrick** [ExLibrisGroup/alma-e-collection-quick-update#13]
Hello,

I ran the app in our Sandbox on 50 e-collections only to append something to the internal description field and have a few issues to report from one run of the app, which I'll try to separate into different issues. 

Out of the 50, 11 gave errors. 9 of the errors are in this form: "ID 61535210010001701 could not be updated: Electronic collection group proxy enable valid values: [1,2,0]". However, the 9 collections with errors about group proxy values actually did update the internal description field.

Two errors are different. One is about interface name valid values, and one is about license valid values (I've attached a copy of the error log it displayed). These two collections did not update at all. I created a set of just the two that didn't update and re-ran the append function and got the same errors. 

Thanks,
Martin Patrick (University of Minnesota)
[umn_cloud_app_errors.txt](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/files/5888964/umn_cloud_app_errors.txt)

**Comment by jweisman** [comment]
Thanks for your report @martinpatrick . We're looking into it.

**Comment by jweisman** [comment]
Hi @martinpatrick - looks like this is bringing up some problems with your data. Can I ask you to have a support case opened and let us know here what the case number is? Then we can work with you on the data issues.

Thanks.

**Comment by jweisman** [comment]
Closing - please reopen if there's still an issue.
