### ISSUE TITLE
The  Cloud App E-collection Quick Update - Counter Platform field is currently free text it should be  should be a drop down of available counter reports just like in the electronic collection editor

### ISSUE THREAD

**Issue by YoelKortick** [ExLibrisGroup/alma-e-collection-quick-update#17]
The  Cloud App E-collection Quick Update - Counter Platform field is currently free text it should be  should be a drop down of available counter reports just like in the electronic collection editor
![image](https://user-images.githubusercontent.com/13975746/116085805-dfd59d80-a6a7-11eb-9f43-057b174cdc15.png)

**Comment by jweisman** [comment]
Hi Yoel- it looks like it is already a drop down:

<img width="406" alt="Screen Shot 2021-04-28 at 6 21 22 " src="https://user-images.githubusercontent.com/80420/116341683-06035680-a7ea-11eb-978d-5ed61445923d.png">

**Comment by YoelKortick** [comment]
Josh you are correct it already is a dropdown apparently this was checked in a place where there were no counter platforms this there were no options

***@***.***D73BFC.AF849CA0]
