### ISSUE TITLE
Support to edit Service 'Active Until' date field

### ISSUE THREAD

**Issue by fionatinto** [ExLibrisGroup/alma-e-collection-quick-update#24]
Hiya!

In the Alma e-collection quick update Cloud App, would it be possible to introduce support to edit (clear / replace) the 'Active Until' date .  We have a situation where 18 collections of JSTOR content that were made freely available during the pandemic were due to have access end on 30th June 2021, but it has been pushed back to 30th June 2022.  If a situation like this crops up again, it would be great to be able to change these in bulk. 

Thanks,
Fiona
<img width="957" alt="Electronic Service Editor active until date" src="https://user-images.githubusercontent.com/77116841/124301628-fee52580-db57-11eb-8460-073fa1e8013c.PNG">

**Comment by jweisman** [comment]
Hi @fionatinto - thanks for your request. We added these two fields in the [latest release](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/releases/tag/v1.3.0). Let us know if there are any issues.

**Comment by fionatinto** [comment]
Josh,

Thanks very much for this!  I've tested.  Clearing the date works fine.  When I replace the 'Active Until' date though, it is consistently entering a date 1 day prior to the date I selected from the calendar in the cloud app.  I've attached screenshots.  Is this a bug ; or is this deliberate in that it's saying 'if you want it to be inactive by on e.g. 31st June then the date you need to enter in Alma is 30th June'?  (Or is this just an error and I'm really overthinking it....?  I get in such a fankle trying to work out whether stuff switches off at midnight at the beginning of  date or the end of a date.... )
[Support to edit Service 'Active Until' date field - attachment 05-07-2021.docx](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/files/6764806/Support.to.edit.Service.Active.Until.date.field.-.attachment.05-07-2021.docx)

Ta,
Fiona

**Comment by jweisman** [comment]
Thanks- checking.....

**Comment by jweisman** [comment]
Thanks for pointing this out @fionatinto . I think we've squashed that bug. Let us know if you still see an issue.
