### ISSUE TITLE
Alma e-Collection quick update - Service Fields> Public note > 'Clear' not working

### ISSUE THREAD

**Issue by fionatinto** [ExLibrisGroup/alma-e-collection-quick-update#30]
Hi Ex Libris,

We're finding that the 'Clear' option isn't working correctly for Service Fields > Public Note.

When we select the 'Clear' dropdown for Service Fields > Public Notes (snip 1 attachment), we are advised that the job has completed successfully (snip 2), but when we then check in Alma the Electronic Service Public Note we are trying to remove is still there (snip 3). 

Could you investigate?

Thanks,
Fiona
<img width="960" alt="snip" src="https://user-images.githubusercontent.com/77116841/138726484-d303ecbe-547c-437f-ae0d-0de270a896ca.PNG">
<img width="960" alt="Snip 2" src="https://user-images.githubusercontent.com/77116841/138726684-64d2dfdd-d0c2-483e-ba22-8d9040049e64.PNG">
<img width="960" alt="Snip 3" src="https://user-images.githubusercontent.com/77116841/138727100-06f4e4b3-2206-4934-9a16-147e2b67bad4.PNG">

**Comment by jweisman** [comment]
Hi @fionatinto - thanks for your note. Very curious- I tried this in my Alma environment and the public note was cleared. 

![Screen Shot 2021-10-26 at 16 09 58 ](https://user-images.githubusercontent.com/80420/138885580-a0580bca-4ed1-42a3-ad87-9680c7a07771.png)

Can we check this in your environment? If so, can you provide your institution code and whether it's production or sandbox?

**Comment by fionatinto** [comment]
Hi Josh,

That is odd!  I'm getting the same problem using both Sandbox and Production Almas. I'm checking with our Systems team if it would be OK for you to have access.

In the meantime…   I deleted the note manually from the collections as I wasn’t sure how long it would take for this to get sorted.  So that we have something to test with, I’ve added a wee test note back into the Service Public Note field of two collections (the two highlighted in the spreadsheet).    I’ve attached screenshots of what I’m doing just in case there is anything very obvious that I’m doing wrong!

I’ll let you know when I’ve heard back from our systems team.

Thanks,
Fiona

[ECOLLECTION QUICK UPDATE ISSUE 30 - SERVICE NOTE FIELD NOT CLEARING.docx](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/files/7418854/ECOLLECTION.QUICK.UPDATE.ISSUE.30.-.SERVICE.NOTE.FIELD.NOT.CLEARING.docx)
[e-collection quick update test collections.xlsx](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/files/7418855/e-collection.quick.update.test.collections.xlsx)

**Comment by fionatinto** [comment]
Hi Josh,

Further to my note a minute ago:

- I'm hitting the same problem both in sandbox and production Alma's
- our institution ID is 44STRATH_INST .  Our systems team said there's no problem sharing the institution ID with you, but if you need some other level of access, an account or whatever we’ll need to know what that is and how long he needs it for. 

So, if you need anything else please let me know.

Thanks!
Fiona

**Comment by jweisman** [comment]
Hi @fionatinto - I tried clearing the public note from the first entry in the test collection file: 61159388950002996. I first added one in Alma and then used the Cloud App to remove it.

![Screen Shot 2021-10-27 at 10 46 51 ](https://user-images.githubusercontent.com/80420/139022727-8c529224-9dab-4e88-9579-04debcf04db0.png)

Can you try the same actions and let us know what you see? Thanks.

**Comment by fionatinto** [comment]
Hi Josh,

Ah! I think we are talking at slightly cross-purposes.  In Alma you have electronic collections and attached those are the electronic services.  There is a public note field at both Electronic Collection level and a public note field at Electronic Service level.  See attached screenshots that show this in Alma.  Based on the screenshot you have sent me, and looking at the history - I can see that you have added and removed the Electronic Collection public note against collection 61159388950002996.

I have just tested using the E-Collection Quick Update to edit the electronic collection public note and I am able to both successfully add and remove a public note at electronic collection level using the cloud app.  But for the Public Note at electronic service level that is not the case - I can add the note successfully using the cloud app, but I can't clear it again.  So when you go to use the Cloud App, at the stage where you select the fields you wish to edit, the 3rd option is Public Note, but that is the Public Note at electronic collection level.  If you keep scrolling down the field options, you get to a sub heading Service Fields, and then there is another Public Note field option, which is the electronic service public note.

Is that why we're getting different results when testing - you are testing using the collection Public Note, whereas I am trying to edit the service Public Note?

Kind regards,
Fiona

[Alma e-collection quick update issue 30 - electronic collections and electronic services.docx](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/files/7424405/Alma.e-collection.quick.update.issue.30.-.electronic.collections.and.electronic.services.docx)

**Comment by jweisman** [comment]
Indeed- it helps to be talking about the same thing! : )

I've reproduced the issue and it appears to be a problem with the underlying Alma API. I'm checking with my colleagues and will get back to you.

**Comment by fionatinto** [comment]
Great, thanks Josh! :)

Fiona

**Comment by jweisman** [comment]
Hi @fionatinto - quick update to let you know this should be fixed in the Alma January release. You should be able to check it in the sandbox from December 19th.
