### ISSUE TITLE
E-Collections Quick Update not working 03-12-2021

### ISSUE THREAD

**Issue by fionatinto** [ExLibrisGroup/alma-e-collection-quick-update#31]
Hi Josh/Team,

I went to test following resolution of tickets #24 and #30 , but am finding that I can't successfully run any job using Alma e-collection quick update.  I've tried editing a few different fields in sandbox and live Almas on both Community Zone and local electronic collections and with every attempt the job just didn't run.  I selected my collections I wanted to edit, set the fields and values that I wanted to change, and then clicked the 'Update # E-Collections' button and the loading bar is getting to half way round and then just not finishing so the job doesn't actually run.

I'll try and test again next week in case it's just systems on strike approaching 5pm on a Friday - but just in case it's more than that I thought I'd just log this ticket now in case I don't get a chance next week.  Hopefully it's just a temporary glitch and will sort itself (though equally, if that is the case then apologies for wasting your time with this ticket!).

Fiona

**Comment by fionatinto** [comment]
[E-Collections Quick Update not working 03-12-21.docx](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/files/7650905/E-Collections.Quick.Update.not.working.03-12-21.docx)

**Comment by jweisman** [comment]
HI @fionatinto - looks like there is some error when retrieving the "Manchester Gothic Open Access eBook Collection" collection. If you only update the "Manchester Gothic eBook Collection" it works well.

I will continue looking into why the API call for the Open Access collection fails.

**Comment by jweisman** [comment]
Hi @fionatinto - I checked and it seems that there was a temporary glitch in the PSB environment. Can you check to confirm both collections are working now?
