### ISSUE TITLE
Cannot update field at Service level without also editing Electronic Collection level.

### ISSUE THREAD

**Issue by niftyt** [ExLibrisGroup/alma-e-collection-quick-update#33]
Cannot seem to update Service Fields without also updating a Electronic Collection field.
This could be an issue with the API rather than the Cloud App?

Am trying to update the Proxy Enable and Proxy fields for a group of electronic collections.
This consistently fails.
When I then also edit a field at the Electronic Collection level the collections update.

**Comment by jweisman** [comment]
Hi @niftyt - we released a [new version](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/releases/tag/1.4.1) which should allow you to update service fields only. Let us know how it goes for you.

**Comment by niftyt** [comment]
I was able to update the service without needing to edit the electronic collection.
Thanks so much for the prompt fix.
