### ISSUE TITLE
Using this CloudApp changes other values than what is specified

### ISSUE THREAD

**Issue by ulrikkeo** [ExLibrisGroup/alma-e-collection-quick-update#36]
Hi, 

I originally reported this in a comment to another case, which apparently was solved last year and closed when I added my comment, but we have experienced this issue too, in two separate instances last week, and I just recreated the issue in our Sandbox to make sure I wasn't crazy. Our institution is University of Oslo, our Alma environment is EU01. When running this cloud app, fields are updated which I didn't change or intend to have changed when updating another field.

1. In first instance I wanted to add a public note to our Wiley collections. I added it on Collection Level, but the history of the Service shows that the following was also updated (in some instances we did have automatically activate, so it was changed from YES to - but the issue is the same );
Activate new portfolios automatically CHANGED FROM | No | TO -
Crossref enabled CHANGED FROM | INHERIT | TO -
Proxy enabled CHANGED FROM | Yes | TO -
Proxy selected CHANGED FROM | DEFAULT | TO -
Service temporarily unavailable CHANGED FROM | No | TO -

IDs of collections changed:
61173720490002204
61202358850002204
61213183250002204
61269426930002204
61266135880002204

2. In the second instance I updated about 17 e-book collections changing activate new portfolios from YES to NO, but the following was changed:
Crossref enabled | INHERIT | -
Proxy enabled | Yes | -
Proxy selected | DEFAULT | -

Activate new portfolios automatically | Yes | No

3. See attached images from when I tried to recreate the issue in our sandbox, just adding a note, and changing the same fields as above in the process.

Kind regards,
Ulrikke Greve Olufsen

![2022-01-31 11_22_45-Window](https://user-images.githubusercontent.com/17887735/151789106-a10fb000-387b-4265-999f-1864ea82c0aa.png)

![2022-01-31 11_45_00-Window](https://user-images.githubusercontent.com/17887735/151789121-f4cb5bab-7075-43f3-af21-91408d54f94b.png)

![2022-01-31 11_45_28-Window](https://user-images.githubusercontent.com/17887735/151789137-72b8bf7e-d3ac-4ab1-84b8-8480e890513e.png)

**Comment by ulrikkeo** [comment]
Hi, I was just wondering whether you were able to replicate this bug and have had a chance to look at this yet?

Kind regards, 
Ulrikke

**Comment by mgobat** [comment]
Hi @ulrikkeo...
We are working through this defect, along with another.
