### ISSUE TITLE
For Proxy Selected Field- Need to allow for "Default" option

### ISSUE THREAD

**Issue by mar1ll10n** [ExLibrisGroup/alma-e-collection-quick-update#4]
Hello,

Upon testing this Cloud app, I noticed that the "Default" option is not available for selection. Even though we only have one proxy setup at this time, we generally prefer to use the "Default" option in Alma rather than the specific named proxy. Are there any plans to make the "Default" option available within the Cloud App?

Thanks
-M

**Comment by jweisman** [comment]
Hi @mar1ll10n . We added the Default option for proxies. Hope this helps.
