### ISSUE TITLE
App not showing options

### ISSUE THREAD

**Issue by markmounts** [ExLibrisGroup/alma-e-collection-quick-update#5]
I was able to install the app in the sandbox and it shows the selection of electronic resources when I am viewing the list of resources but in the production version of Alma I installed the app but the selection of electronic resources is not appearing when I am viewing the list of resources from a search. I have tried reinstalling the app a few times.
[dcl.alma.exlibrisgroup.com-1605795079119.log](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/files/5567251/dcl.alma.exlibrisgroup.com-1605795079119.log)

**Comment by jweisman** [comment]
Hi @markmounts . Thanks for your comment. Could you perhaps provide a screencast of the issue happening? Also please let us know which environment you're using (institution, user) so we can look into it.

**Comment by markmounts** [comment]
The problem does not exist in Chrome or Firefox. The browser I normally use is Vivaldi which is where the problem exists. I have attached what it looks like when it works and when it doesn't. 

Instance Name: NA01
Dartmouth College
Mounts, Mark  
Record type Public 
Account Type External 
User group Staff 
Identity Service Not Used 
Owner PL

![firefox-chrome](https://user-images.githubusercontent.com/2528950/99969240-30974200-2d68-11eb-9ae8-f1c5aada443b.png)
![vivaldi-3 4 2066 106-macOS-10 15 7](https://user-images.githubusercontent.com/2528950/99969356-53295b00-2d68-11eb-8664-9c97733c45d1.png)

**Comment by markmounts** [comment]
the app is now working in Vivaldi.

**Comment by jweisman** [comment]
That's good- glad to hear. I also tested it in Vivaldi (first time using that browser : ) ) and it seemed to work for me too. Let us know if you run into any more issues.
