### ISSUE TITLE
Clear for Service unavailable date

### ISSUE THREAD

**Issue by fionatinto** [ExLibrisGroup/alma-e-collection-quick-update#8]
Clear for Service unavailable date isn't working.  It's returning 'e-collection(s) could not be updated.' error and not clearing the date from the field.
Details information is I think slightly cut off in the browser, but what I can see reads as follows:
ID 62111538880002996 could not be updated: (was java.lang.IllegalArgumentException) (through reference chain: com.exlibris.alma.ws.jaxb.electronicservice.ElectronicSer

**Comment by jweisman** [comment]
Hi @fionatinto . Thanks for reporting this. We [released](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/releases/tag/v1.2.0) a small fix for this bug so it should be OK now.

**Comment by fionatinto** [comment]
> Hi @fionatinto . Thanks for reporting this. We [released](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/releases/tag/v1.2.0) a small fix for this bug so it should be OK now.

Hi @jweisman  - I've just tested this in the sandbox.  I'm no longer getting an error, but the 'Clear' function for Service Unavailable Date still isn't working.  I've attached screenshots (I hope - not entirely sure if the attachment uploaded successfully). Could you investigate further?
[Alma e-collection quick update - service unavailable date Clear problem.docx](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/files/5795285/Alma.e-collection.quick.update.-.service.unavailable.date.Clear.problem.docx)

**Comment by jweisman** [comment]
Thanks @fionatinto - I see the app is sending the right value but it's not being updated. We'll investigate further.

**Comment by jweisman** [comment]
Hi @fionatinto . Sorry for the delay on this- took us some time to investigate. The problem lies with the API that the Cloud App uses. I've discussed with my colleague @ori229 and we are aiming to get this fixed in the Alma May release. Sorry for the inconvenience and thanks for the bug report.

**Comment by fionatinto** [comment]
Hi Josh,

That's great - thanks for the update. I'll look forward to a fix in the May release.

Thanks very much!
Fiona

**Comment by jweisman** [comment]
Hi @fionatinto - this should be working well now. Please let us know if there's still a problem and we'll reopen the issue.

Thanks.
