### ISSUE TITLE
electronic service fields - enhancement request

### ISSUE THREAD

**Issue by fionatinto** [ExLibrisGroup/alma-e-collection-quick-update#9]
This app is really useful.  Would it be possible to add other Service Fields?  Below is what I would like to see added. Happy to provide more information if needed, though I am an Alma user rather than a developer.

1. the Electronic Service Authentication Note 

2. the proxy fields in the Electronic Service  (rather than the proxy fields against the electronic collection - because for many types of Alma electronic collection, the proxy fields at Electronic Service level are the ones that have the functional role). Specifically, the fields in Alma are:
- Proxy enabled (yes / no field)
- Proxy selected (dropdown where you select the relevant proxy service you wish to use)

**Comment by jweisman** [comment]
Hi @fionatinto . Glad the app is helpful for you.

We released a [minor version](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/releases/tag/v1.2.0) which includes these new service fields. Let us know how it goes for you.

Thanks.

**Comment by fionatinto** [comment]
> Hi @fionatinto . Glad the app is helpful for you.
> 
> We released a [minor version](https://github.com/ExLibrisGroup/alma-e-collection-quick-update/releases/tag/v1.2.0) which includes these new service fields. Let us know how it goes for you.
> 
> Thanks.

Hi @jweisman ,

I've just tested the applying / removing the Service proxy and Service authentication note in the sandbox.  They both work as I'd hoped.  Thanks so much - this functionality is a massive help to me.

Thanks,
Fiona
